version: "3.8"
services:
  lats:
    container_name: lats
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "6868:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod